name: Tests

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8" ]


    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        env:
          REDIS_PORT: ${{ vars.REDIS_PORT }}
          REDIS_HOST: ${{ vars.REDIS_HOST }}
          REDIS_DB: ${{ vars.REDIS_DB }}

        run: |
          export REDIS_PORT=${{ vars.REDIS_PORT }}
          export REDIS_HOST=${{ vars.REDIS_HOST }}
          export REDIS_DB=${{ vars.REDIS_DB }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt



      - name: Test with pytest
        run: |
          pytest